package com.obv.qa.util;

import com.obv.qa.base.TestBase;
import org.apache.commons.mail.*;
import static com.obv.qa.base.TestBase.*;
import static com.obv.qa.base.TestBase.email;

public class SendEmail {
    public static void NotifyFailure(String methodName, String className) throws EmailException {


        System.out.println("Starting to send mail!!");
        Email email = new SimpleEmail();
        email.setHostName("smtp.gmail.com");
        email.setSmtpPort(587);//465
        email.setAuthenticator(new DefaultAuthenticator(sendEmailId, sendEmailPass));
        email.setSSLOnConnect(true);
        email.setFrom(String.valueOf(email));
        email.setSubject("TestMail");

        String message="Greetings from Droom OBV\n\nThis is an autogenerated mail sent because of a test case failure in OrangeBookValue Automation.\n\n"+
                "Failure Details:\n"+"Test Class Name: "+className+"\n\n"+"Test Method Name: "
                +methodName+"\n\nKindly check Extent Report for more details."
                +"\n\nThanks and Regards\nOrange Book Value Automation\nDroom";
        email.setMsg(message);
        email.addTo(sendEmailTo);
        email.send();

        System.out.println("Email sent");
    }

    public static void sendEmailWithAttachment() throws EmailException, InterruptedException {
        // Create the attachment

        System.out.println("Waiting for report to be updated...");
        Thread.sleep(10000);
        EmailAttachment attachment = new EmailAttachment();

        System.out.println("Composing Email");
        System.out.println("Retrieving Report");

        attachment.setPath("test-output/Extent.html");
        attachment.setDisposition(EmailAttachment.ATTACHMENT);
        attachment.setDescription("Automation Report");
        attachment.setName("Report");




        // Create the email message
        MultiPartEmail email = new MultiPartEmail();


        System.out.println("Setting Host Name");
        email.setHostName("smtp.gmail.com");

        System.out.println("Setting Port Number");
        email.setSmtpPort(587);//465
        email.setAuthenticator(new DefaultAuthenticator(sendEmailId, sendEmailPass));
        email.setSSLOnConnect(true);
        email.setFrom(String.valueOf(email));
        email.setSubject("OBV Automation Report");
        String message="Greetings from Droom OBV\n\nThis is an autogenerated mail sent from OBV automation.\n\n"
                +"\n\nPlease find attached the Extent Report for the automation results."
                +"\n\nThanks and Regards\nOrange Book Value Automation\nDroom";
        email.setMsg(message);
        email.addTo(sendEmailTo);

        // add the attachment
        System.out.println("Adding Attachment...");
        email.attach(attachment);

        // send the email
        email.send();

        System.out.println("Email Sent");
    }
}


